// <auto-generated />
using Cirkla_DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cirkla_DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cirkla_DAL.Models.ItemPictures.ItemPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemPictures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 25,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 9,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 29,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 18,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 29,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 6,
                            ItemId = 13,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 7,
                            ItemId = 12,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 8,
                            ItemId = 3,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 9,
                            ItemId = 15,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 10,
                            ItemId = 9,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 11,
                            ItemId = 10,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 12,
                            ItemId = 29,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 13,
                            ItemId = 14,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 14,
                            ItemId = 6,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 15,
                            ItemId = 12,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 16,
                            ItemId = 18,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 17,
                            ItemId = 28,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 18,
                            ItemId = 22,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 19,
                            ItemId = 29,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 20,
                            ItemId = 13,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 21,
                            ItemId = 3,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 22,
                            ItemId = 14,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 23,
                            ItemId = 15,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 24,
                            ItemId = 21,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 25,
                            ItemId = 14,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 26,
                            ItemId = 23,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 27,
                            ItemId = 18,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 28,
                            ItemId = 7,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 29,
                            ItemId = 4,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 30,
                            ItemId = 17,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 31,
                            ItemId = 22,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 32,
                            ItemId = 17,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 33,
                            ItemId = 21,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 34,
                            ItemId = 18,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 35,
                            ItemId = 13,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 36,
                            ItemId = 24,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 37,
                            ItemId = 19,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 38,
                            ItemId = 9,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 39,
                            ItemId = 20,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 40,
                            ItemId = 18,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 41,
                            ItemId = 23,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 42,
                            ItemId = 12,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 43,
                            ItemId = 21,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 44,
                            ItemId = 21,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 45,
                            ItemId = 13,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 46,
                            ItemId = 22,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 47,
                            ItemId = 17,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 48,
                            ItemId = 22,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 49,
                            ItemId = 14,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 50,
                            ItemId = 19,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 51,
                            ItemId = 22,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 52,
                            ItemId = 28,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 53,
                            ItemId = 18,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 54,
                            ItemId = 26,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 55,
                            ItemId = 11,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 56,
                            ItemId = 17,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 57,
                            ItemId = 21,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 58,
                            ItemId = 27,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 59,
                            ItemId = 1,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 60,
                            ItemId = 19,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 61,
                            ItemId = 3,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 62,
                            ItemId = 19,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 63,
                            ItemId = 27,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 64,
                            ItemId = 17,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 65,
                            ItemId = 13,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 66,
                            ItemId = 6,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 67,
                            ItemId = 2,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 68,
                            ItemId = 21,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 69,
                            ItemId = 10,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 70,
                            ItemId = 17,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 71,
                            ItemId = 7,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 72,
                            ItemId = 14,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 73,
                            ItemId = 11,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 74,
                            ItemId = 10,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 75,
                            ItemId = 26,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 76,
                            ItemId = 13,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 77,
                            ItemId = 22,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 78,
                            ItemId = 15,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 79,
                            ItemId = 19,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 80,
                            ItemId = 12,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 81,
                            ItemId = 16,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 82,
                            ItemId = 22,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 83,
                            ItemId = 1,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 84,
                            ItemId = 28,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 85,
                            ItemId = 3,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 86,
                            ItemId = 14,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 87,
                            ItemId = 17,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 88,
                            ItemId = 29,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 89,
                            ItemId = 10,
                            Url = "https://loremflickr.com/420/420/tool"
                        },
                        new
                        {
                            Id = 90,
                            ItemId = 25,
                            Url = "https://loremflickr.com/420/420/tool"
                        });
                });

            modelBuilder.Entity("Cirkla_DAL.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "1st thingamagig",
                            OwnerId = 7,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 2,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "2st thingamagig",
                            OwnerId = 2,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 3,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "3st thingamagig",
                            OwnerId = 6,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 4,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "4st thingamagig",
                            OwnerId = 3,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 5,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "5st thingamagig",
                            OwnerId = 1,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 6,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "6st thingamagig",
                            OwnerId = 8,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 7,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "7st thingamagig",
                            OwnerId = 9,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 8,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "8st thingamagig",
                            OwnerId = 5,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 9,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "9st thingamagig",
                            OwnerId = 4,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 10,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "10st thingamagig",
                            OwnerId = 7,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 11,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "11st thingamagig",
                            OwnerId = 1,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 12,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "12st thingamagig",
                            OwnerId = 6,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 13,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "13st thingamagig",
                            OwnerId = 3,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 14,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "14st thingamagig",
                            OwnerId = 8,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 15,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "15st thingamagig",
                            OwnerId = 1,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 16,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "16st thingamagig",
                            OwnerId = 3,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 17,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "17st thingamagig",
                            OwnerId = 9,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 18,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "18st thingamagig",
                            OwnerId = 3,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 19,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "19st thingamagig",
                            OwnerId = 6,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 20,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "20st thingamagig",
                            OwnerId = 3,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 21,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "21st thingamagig",
                            OwnerId = 4,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 22,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "22st thingamagig",
                            OwnerId = 7,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 23,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "23st thingamagig",
                            OwnerId = 8,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 24,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "24st thingamagig",
                            OwnerId = 3,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 25,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "25st thingamagig",
                            OwnerId = 4,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 26,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "26st thingamagig",
                            OwnerId = 4,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 27,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "27st thingamagig",
                            OwnerId = 1,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 28,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "28st thingamagig",
                            OwnerId = 5,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 29,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "29st thingamagig",
                            OwnerId = 6,
                            Specifications = ""
                        },
                        new
                        {
                            Id = 30,
                            Category = "General stuff",
                            Description = "To be, or to takes, when he himself might his quietus makes us rather bear those ills we have, the native hue of resolution is sicklied o'er with the dreams may come when he himself might his quietus make with and their currents turn awry, and the slings and moment with this mortal coil, must give us pause.",
                            Model = "gobbledygook",
                            Name = "30st thingamagig",
                            OwnerId = 2,
                            Specifications = ""
                        });
                });

            modelBuilder.Entity("Cirkla_DAL.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Melrose Place 1",
                            Email = "User1.UserSon1@mail.com",
                            FirstName = "User1",
                            LastName = "UserSon1",
                            PhoneNumber = "0920 111 111",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "11111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Melrose Place 2",
                            Email = "User2.UserSon2@mail.com",
                            FirstName = "User2",
                            LastName = "UserSon2",
                            PhoneNumber = "0920 222 222",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "22222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Melrose Place 3",
                            Email = "User3.UserSon3@mail.com",
                            FirstName = "User3",
                            LastName = "UserSon3",
                            PhoneNumber = "0920 333 333",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "33333"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Melrose Place 4",
                            Email = "User4.UserSon4@mail.com",
                            FirstName = "User4",
                            LastName = "UserSon4",
                            PhoneNumber = "0920 444 444",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "44444"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Melrose Place 5",
                            Email = "User5.UserSon5@mail.com",
                            FirstName = "User5",
                            LastName = "UserSon5",
                            PhoneNumber = "0920 555 555",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "55555"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Melrose Place 6",
                            Email = "User6.UserSon6@mail.com",
                            FirstName = "User6",
                            LastName = "UserSon6",
                            PhoneNumber = "0920 666 666",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "66666"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Melrose Place 7",
                            Email = "User7.UserSon7@mail.com",
                            FirstName = "User7",
                            LastName = "UserSon7",
                            PhoneNumber = "0920 777 777",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "77777"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Melrose Place 8",
                            Email = "User8.UserSon8@mail.com",
                            FirstName = "User8",
                            LastName = "UserSon8",
                            PhoneNumber = "0920 888 888",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "88888"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Melrose Place 9",
                            Email = "User9.UserSon9@mail.com",
                            FirstName = "User9",
                            LastName = "UserSon9",
                            PhoneNumber = "0920 999 999",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "99999"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Melrose Place 10",
                            Email = "User10.UserSon10@mail.com",
                            FirstName = "User10",
                            LastName = "UserSon10",
                            PhoneNumber = "0920 101010 101010",
                            ProfilePictureURL = "https://avatar.iran.liara.run/public",
                            ZipCode = "1010101010"
                        });
                });

            modelBuilder.Entity("Cirkla_DAL.Models.ItemPictures.ItemPicture", b =>
                {
                    b.HasOne("Cirkla_DAL.Models.Items.Item", "Item")
                        .WithMany("Pictures")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Cirkla_DAL.Models.Items.Item", b =>
                {
                    b.HasOne("Cirkla_DAL.Models.Users.User", "Owner")
                        .WithMany("Items")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Cirkla_DAL.Models.Items.Item", b =>
                {
                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("Cirkla_DAL.Models.Users.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
